# Generated by Django 4.1 on 2022-09-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videocall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
