# Generated by Django 4.1 on 2022-09-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videocall', '0003_hosts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='isAdmin',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
